import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import type { Metadata } from "next";
import { Baloo_2 } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/hooks/useAuth";

const baloo = Baloo_2({
  variable: "--font-baloo-2",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${baloo.variable} antialiased`}
      >
        <AuthProvider>
          <main className="flex flex-col min-h-screen">
            <Header />
            {children}
            <Footer />
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
