"""version 1.0.0

Revision ID: 941560c1bffe
Revises: 
Create Date: 2025-12-22 20:16:23.726739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941560c1bffe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('bt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bt_token', sa.String(length=500), nullable=False),
    sa.Column('bt_created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('bt_id'),
    sa.UniqueConstraint('bt_token')
    )
    op.create_table('brands',
    sa.Column('brand_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('brand_id'),
    sa.UniqueConstraint('brand_name')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_parent_id', sa.Integer(), nullable=True),
    sa.Column('category_image_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_parent_id'], ['categories.category_id'], name='fk_categories_parent_id'),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('medias',
    sa.Column('media_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_url', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('media_ref_type', sa.String(length=50), nullable=False),
    sa.Column('media_ref_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('media_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notification_title', sa.String(length=100), nullable=False),
    sa.Column('notification_message', sa.Text(), nullable=False),
    sa.Column('notification_created_at', sa.DateTime(), nullable=True),
    sa.Column('notification_ref_type', sa.String(length=50), nullable=False),
    sa.Column('notification_ref_id', sa.Integer(), nullable=False),
    sa.Column('notification_status', sa.Enum('active', 'inactive', name='notification_status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_notification_ref_id'), 'notifications', ['notification_ref_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_ref_type'), 'notifications', ['notification_ref_type'], unique=False)
    op.create_index(op.f('ix_notifications_notification_status'), 'notifications', ['notification_status'], unique=False)
    op.create_table('otps',
    sa.Column('otp_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('otp_email', sa.String(length=100), nullable=False),
    sa.Column('otp_created_at', sa.DateTime(), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=False),
    sa.Column('otp_is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('otp_id')
    )
    op.create_table('searchs',
    sa.Column('search_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_content', sa.String(length=500), nullable=False),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('search_id'),
    sa.UniqueConstraint('search_content')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=True),
    sa.Column('user_password', sa.String(length=255), nullable=False),
    sa.Column('user_first_name', sa.String(length=100), nullable=True),
    sa.Column('user_last_name', sa.String(length=100), nullable=True),
    sa.Column('user_gender', sa.Enum('male', 'female', 'other', name='user_gender_enum'), nullable=True),
    sa.Column('user_dob', sa.DateTime(), nullable=True),
    sa.Column('user_status', sa.Enum('active', 'inactive', 'banned', name='user_status_enum'), nullable=False),
    sa.Column('user_phone_number', sa.String(length=15), nullable=False),
    sa.Column('user_avatar_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_phone_number')
    )
    op.create_index(op.f('ix_users_user_status'), 'users', ['user_status'], unique=False)
    op.create_table('admins',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_admins_user_id'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('end_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_end_users_user_id'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('has_notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('notification_user_id', sa.Integer(), nullable=False),
    sa.Column('notification_read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notification_id'], name='fk_has_notifications_notif_id'),
    sa.ForeignKeyConstraint(['notification_user_id'], ['users.user_id'], name='fk_has_notifications_user_id'),
    sa.PrimaryKeyConstraint('notification_id', 'notification_user_id')
    )
    op.create_table('logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_description', sa.Text(), nullable=True),
    sa.Column('log_timestamp', sa.DateTime(), nullable=True),
    sa.Column('log_user_id', sa.Integer(), nullable=False),
    sa.Column('log_ref_type', sa.String(length=50), nullable=False),
    sa.Column('log_ref_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['log_user_id'], ['users.user_id'], name='fk_logs_user_id'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_logs_log_ref_id'), 'logs', ['log_ref_id'], unique=False)
    op.create_index(op.f('ix_logs_log_ref_type'), 'logs', ['log_ref_type'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_ref_type', sa.String(length=50), nullable=False),
    sa.Column('message_ref_id', sa.Integer(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('message_is_read', sa.Boolean(), nullable=False),
    sa.Column('message_created_at', sa.DateTime(), nullable=False),
    sa.Column('message_updated_at', sa.DateTime(), nullable=False),
    sa.Column('message_receiver_id', sa.Integer(), nullable=False),
    sa.Column('message_sender_id', sa.Integer(), nullable=False),
    sa.Column('message_replied_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_receiver_id'], ['users.user_id'], name='fk_messages_receiver_id'),
    sa.ForeignKeyConstraint(['message_replied_to_id'], ['messages.message_id'], name='fk_messages_replied_to_id'),
    sa.ForeignKeyConstraint(['message_sender_id'], ['users.user_id'], name='fk_messages_sender_id'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_message_ref_id'), 'messages', ['message_ref_id'], unique=False)
    op.create_index(op.f('ix_messages_message_ref_type'), 'messages', ['message_ref_type'], unique=False)
    op.create_table('buyers',
    sa.Column('buyer_point', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['end_users.user_id'], name='fk_buyers_user_id'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('sellers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seller_available_balance', sa.Integer(), nullable=False),
    sa.Column('receive_method_bin', sa.String(length=100), nullable=True),
    sa.Column('receive_method_banknum', sa.String(length=50), nullable=True),
    sa.Column('receive_method_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['end_users.user_id'], name='fk_sellers_user_id'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('tickets',
    sa.Column('ticket_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_title', sa.String(length=255), nullable=False),
    sa.Column('ticket_description', sa.Text(), nullable=True),
    sa.Column('ticket_status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='ticket_status_enum'), nullable=False),
    sa.Column('ticket_created_at', sa.DateTime(), nullable=True),
    sa.Column('ticket_updated_at', sa.DateTime(), nullable=True),
    sa.Column('ticket_category', sa.String(length=100), nullable=True),
    sa.Column('ticket_rate', sa.Integer(), nullable=True),
    sa.Column('ticket_end_user_id', sa.Integer(), nullable=False),
    sa.Column('ticket_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_admin_id'], ['admins.user_id'], name='fk_tickets_admin_id'),
    sa.ForeignKeyConstraint(['ticket_end_user_id'], ['end_users.user_id'], name='fk_tickets_end_user_id'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_tickets_ticket_status'), 'tickets', ['ticket_status'], unique=False)
    op.create_table('addresses',
    sa.Column('address_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address_is_default', sa.Integer(), nullable=False),
    sa.Column('address_district', sa.String(length=100), nullable=False),
    sa.Column('address_description', sa.String(length=255), nullable=False),
    sa.Column('address_user_name', sa.String(length=100), nullable=False),
    sa.Column('address_user_phone', sa.String(length=15), nullable=False),
    sa.Column('address_province', sa.String(length=100), nullable=False),
    sa.Column('address_buyer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_buyer_id'], ['buyers.user_id'], name='fk_addresses_buyer_id'),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('bid_documents',
    sa.Column('bid_document_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bid_document_description', sa.Text(), nullable=True),
    sa.Column('bid_document_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('bid_seller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bid_seller_id'], ['sellers.user_id'], name='fk_bid_documents_seller_id'),
    sa.PrimaryKeyConstraint('bid_document_id')
    )
    op.create_table('block_sellers',
    sa.Column('bs_buyer_id', sa.Integer(), nullable=False),
    sa.Column('bs_seller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bs_buyer_id'], ['buyers.user_id'], name='fk_block_sellers_buyer_id'),
    sa.ForeignKeyConstraint(['bs_seller_id'], ['sellers.user_id'], name='fk_block_sellers_seller_id'),
    sa.PrimaryKeyConstraint('bs_buyer_id', 'bs_seller_id')
    )
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_ref_type', sa.String(length=50), nullable=False),
    sa.Column('report_reason', sa.Text(), nullable=True),
    sa.Column('report_created_at', sa.DateTime(), nullable=True),
    sa.Column('report_updated_at', sa.DateTime(), nullable=True),
    sa.Column('report_status', sa.Enum('pending', 'reviewed', 'resolved', name='report_status_enum'), nullable=False),
    sa.Column('report_ref_id', sa.Integer(), nullable=True),
    sa.Column('report_buyer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_buyer_id'], ['buyers.user_id'], name='fk_reports_buyer_id'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index('idx_report_type_status', 'reports', ['report_ref_type', 'report_status'], unique=False)
    op.create_index(op.f('ix_reports_report_ref_id'), 'reports', ['report_ref_id'], unique=False)
    op.create_index(op.f('ix_reports_report_ref_type'), 'reports', ['report_ref_type'], unique=False)
    op.create_index(op.f('ix_reports_report_status'), 'reports', ['report_status'], unique=False)
    op.create_table('shops',
    sa.Column('shop_name', sa.String(length=100), nullable=False),
    sa.Column('shop_seller_id', sa.Integer(), nullable=False),
    sa.Column('shop_address', sa.String(length=255), nullable=True),
    sa.Column('shop_logo_url', sa.String(length=255), nullable=True),
    sa.Column('shop_banner_url', sa.String(length=255), nullable=True),
    sa.Column('shop_introduce', sa.Text(), nullable=True),
    sa.Column('shop_hotline', sa.String(length=50), nullable=True),
    sa.Column('shop_created_at', sa.DateTime(), nullable=False),
    sa.Column('shop_province', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['shop_seller_id'], ['sellers.user_id'], name='fk_shops_seller_id'),
    sa.PrimaryKeyConstraint('shop_name', 'shop_seller_id'),
    sa.UniqueConstraint('shop_seller_id')
    )
    op.create_table('titles',
    sa.Column('title_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_name', sa.String(length=255), nullable=False),
    sa.Column('title_order', sa.Integer(), nullable=False),
    sa.Column('title_description', sa.String(length=500), nullable=True),
    sa.Column('title_status', sa.String(length=255), nullable=False),
    sa.Column('title_seller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['title_seller_id'], ['sellers.user_id'], name='fk_titles_seller_id'),
    sa.PrimaryKeyConstraint('title_id'),
    sa.UniqueConstraint('title_name')
    )
    op.create_table('vouchers',
    sa.Column('voucher_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voucher_code', sa.String(length=50), nullable=False),
    sa.Column('voucher_remaining_quantity', sa.Integer(), nullable=False),
    sa.Column('voucher_end_date', sa.DateTime(), nullable=False),
    sa.Column('voucher_start_date', sa.DateTime(), nullable=False),
    sa.Column('voucher_total_quantity', sa.Integer(), nullable=False),
    sa.Column('voucher_description', sa.Text(), nullable=True),
    sa.Column('voucher_discount_type', sa.Enum('percentage', 'fixed_amount', name='voucher_discount_type_enum'), nullable=False),
    sa.Column('voucher_discount_value', sa.Integer(), nullable=False),
    sa.Column('voucher_min_order_value', sa.Integer(), nullable=True),
    sa.Column('voucher_max_discount_value', sa.Integer(), nullable=True),
    sa.Column('voucher_ref_type', sa.String(length=100), nullable=True),
    sa.Column('voucher_ref_id', sa.Integer(), nullable=True),
    sa.Column('voucher_name', sa.String(length=100), nullable=False),
    sa.Column('voucher_use_max', sa.Integer(), nullable=True),
    sa.Column('voucher_seller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['voucher_seller_id'], ['sellers.user_id'], name='fk_vouchers_seller_id'),
    sa.PrimaryKeyConstraint('voucher_id'),
    sa.UniqueConstraint('voucher_code')
    )
    op.create_index(op.f('ix_vouchers_voucher_discount_type'), 'vouchers', ['voucher_discount_type'], unique=False)
    op.create_index(op.f('ix_vouchers_voucher_ref_id'), 'vouchers', ['voucher_ref_id'], unique=False)
    op.create_index(op.f('ix_vouchers_voucher_ref_type'), 'vouchers', ['voucher_ref_type'], unique=False)
    op.create_table('withdrawal_histories',
    sa.Column('withdrawal_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('withdrawal_history_seller_id', sa.Integer(), nullable=False),
    sa.Column('withdrawal_history_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('withdrawal_history_created_at', sa.DateTime(), nullable=True),
    sa.Column('withdrawal_history_method_bin', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['withdrawal_history_seller_id'], ['sellers.user_id'], name='fk_withdrawal_histories_seller_id'),
    sa.PrimaryKeyConstraint('withdrawal_history_id')
    )
    op.create_table('buyer_vouchers',
    sa.Column('buyer_voucher_voucher_id', sa.Integer(), nullable=False),
    sa.Column('buyer_voucher_buyer_id', sa.Integer(), nullable=False),
    sa.Column('buyer_voucher_used_at', sa.DateTime(), nullable=True),
    sa.Column('buyer_voucher_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_voucher_buyer_id'], ['buyers.user_id'], name='fk_buyer_vouchers_buyer_id'),
    sa.ForeignKeyConstraint(['buyer_voucher_voucher_id'], ['vouchers.voucher_id'], name='fk_buyer_vouchers_voucher_id'),
    sa.PrimaryKeyConstraint('buyer_voucher_voucher_id', 'buyer_voucher_buyer_id')
    )
    op.create_table('follow_shops',
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=100), nullable=False),
    sa.Column('shop_seller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.user_id'], name='fk_follow_shops_buyer_id'),
    sa.ForeignKeyConstraint(['shop_name', 'shop_seller_id'], ['shops.shop_name', 'shops.shop_seller_id'], name='fk_follow_shops_shop'),
    sa.PrimaryKeyConstraint('buyer_id', 'shop_name', 'shop_seller_id')
    )
    op.create_index('idx_follow_shops_shop', 'follow_shops', ['shop_name', 'shop_seller_id'], unique=False)
    op.create_table('operating_times',
    sa.Column('operating_time_seller_id', sa.Integer(), nullable=False),
    sa.Column('operating_time_shop_name', sa.String(length=100), nullable=False),
    sa.Column('operating_time_dow', sa.Enum('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'), nullable=False),
    sa.Column('operating_time_opening', sa.Time(), nullable=False),
    sa.Column('operating_time_closing', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['operating_time_seller_id', 'operating_time_shop_name'], ['shops.shop_seller_id', 'shops.shop_name'], name='fk_operating_times_shop', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('operating_time_seller_id', 'operating_time_shop_name', 'operating_time_dow')
    )
    op.create_index('idx_operating_times_shop', 'operating_times', ['operating_time_seller_id', 'operating_time_shop_name'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_buyer_id', sa.Integer(), nullable=False),
    sa.Column('order_total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('order_created_at', sa.DateTime(), nullable=True),
    sa.Column('order_used_point', sa.Integer(), nullable=True),
    sa.Column('order_code', sa.String(length=100), nullable=False),
    sa.Column('order_note', sa.String(length=255), nullable=True),
    sa.Column('order_address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_address_id'], ['addresses.address_id'], name='fk_orders_address_id'),
    sa.ForeignKeyConstraint(['order_buyer_id'], ['buyers.user_id'], name='fk_orders_buyer_id'),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('order_code')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('product_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('product_stock', sa.Integer(), nullable=False),
    sa.Column('product_status', sa.Enum('active', 'inactive', 'discontinued', name='product_status_enum'), nullable=False),
    sa.Column('product_pom', sa.String(length=100), nullable=True),
    sa.Column('product_created_at', sa.DateTime(), nullable=True),
    sa.Column('product_updated_at', sa.DateTime(), nullable=True),
    sa.Column('product_unit', sa.String(length=50), nullable=True),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('product_condition', sa.Integer(), nullable=False),
    sa.Column('product_more_info', sa.Text(), nullable=True),
    sa.Column('product_category_id', sa.Integer(), nullable=False),
    sa.Column('product_shop_seller_id', sa.Integer(), nullable=False),
    sa.Column('product_shop_name', sa.String(length=100), nullable=False),
    sa.CheckConstraint('product_price >= 0', name='check_product_price_positive'),
    sa.CheckConstraint('product_stock >= 0', name='check_product_stock_nonnegative'),
    sa.ForeignKeyConstraint(['product_category_id'], ['categories.category_id'], name='fk_products_category_id'),
    sa.ForeignKeyConstraint(['product_shop_seller_id', 'product_shop_name'], ['shops.shop_seller_id', 'shops.shop_name'], name='fk_products_shop', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index('idx_products_category_status', 'products', ['product_category_id', 'product_status'], unique=False)
    op.create_index('idx_products_shop', 'products', ['product_shop_seller_id', 'product_shop_name'], unique=False)
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.create_index(op.f('ix_products_product_status'), 'products', ['product_status'], unique=False)
    op.create_table('accumulate_points',
    sa.Column('accumulate_points_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('accumulate_points_created_at', sa.DateTime(), nullable=True),
    sa.Column('accumulate_points_number', sa.Integer(), nullable=False),
    sa.Column('accumulate_points_buyer_id', sa.Integer(), nullable=False),
    sa.Column('accumulate_points_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accumulate_points_buyer_id'], ['buyers.user_id'], name='fk_accumulate_points_buyer_id'),
    sa.ForeignKeyConstraint(['accumulate_points_order_id'], ['orders.order_id'], name='fk_accumulate_points_order_id'),
    sa.PrimaryKeyConstraint('accumulate_points_id')
    )
    op.create_table('bid_products',
    sa.Column('bid_product_bid_document_id', sa.Integer(), nullable=False),
    sa.Column('bid_product_product_id', sa.Integer(), nullable=False),
    sa.Column('bid_product_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bid_product_bid_document_id'], ['bid_documents.bid_document_id'], name='fk_bid_products_doc_id'),
    sa.ForeignKeyConstraint(['bid_product_product_id'], ['products.product_id'], name='fk_bid_products_product_id'),
    sa.PrimaryKeyConstraint('bid_product_bid_document_id', 'bid_product_product_id')
    )
    op.create_table('bids',
    sa.Column('bid_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bid_start_date', sa.DateTime(), nullable=False),
    sa.Column('bid_status', sa.Enum('active', 'closed', 'cancelled', name='bid_status_enum'), nullable=False),
    sa.Column('bid_title', sa.Integer(), nullable=False),
    sa.Column('bid_description', sa.Text(), nullable=True),
    sa.Column('bid_end_date', sa.DateTime(), nullable=False),
    sa.Column('bid_price_to', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('bid_price_from', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('bid_place', sa.String(length=255), nullable=True),
    sa.Column('bid_order_id', sa.Integer(), nullable=True),
    sa.Column('bid_buyer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bid_buyer_id'], ['buyers.user_id'], name='fk_bids_buyer_id'),
    sa.ForeignKeyConstraint(['bid_order_id'], ['orders.order_id'], name='fk_bids_order_id'),
    sa.PrimaryKeyConstraint('bid_id')
    )
    op.create_index(op.f('ix_bids_bid_status'), 'bids', ['bid_status'], unique=False)
    op.create_table('favorites',
    sa.Column('favorite_buyer_id', sa.Integer(), nullable=False),
    sa.Column('favorite_product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_buyer_id'], ['buyers.user_id'], name='fk_favorites_buyer_id'),
    sa.ForeignKeyConstraint(['favorite_product_id'], ['products.product_id'], name='fk_favorites_product_id'),
    sa.PrimaryKeyConstraint('favorite_buyer_id', 'favorite_product_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_order_id', sa.Integer(), nullable=False),
    sa.Column('payment_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('payment_method_name', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'completed', 'failed', 'refunded', name='payment_status_enum'), nullable=False),
    sa.Column('payment_trans_id', sa.String(length=100), nullable=True),
    sa.Column('payment_created_at', sa.DateTime(), nullable=True),
    sa.Column('payment_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_order_id'], ['orders.order_id'], name='fk_payments_order_id'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_payment_status'), 'payments', ['payment_status'], unique=False)
    op.create_table('product_brands',
    sa.Column('product_brand_product_id', sa.Integer(), nullable=False),
    sa.Column('product_brand_brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_brand_brand_id'], ['brands.brand_id'], name='fk_product_brands_brand_id'),
    sa.ForeignKeyConstraint(['product_brand_product_id'], ['products.product_id'], name='fk_product_brands_product_id'),
    sa.PrimaryKeyConstraint('product_brand_product_id', 'product_brand_brand_id')
    )
    op.create_table('product_titles',
    sa.Column('pt_product_id', sa.Integer(), nullable=False),
    sa.Column('pt_title_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pt_product_id'], ['products.product_id'], name='fk_product_titles_product_id'),
    sa.ForeignKeyConstraint(['pt_title_id'], ['titles.title_id'], name='fk_product_titles_title_id'),
    sa.PrimaryKeyConstraint('pt_product_id', 'pt_title_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_comment', sa.Text(), nullable=False),
    sa.Column('review_rating', sa.Integer(), nullable=False),
    sa.Column('review_created_at', sa.DateTime(), nullable=True),
    sa.Column('review_updated_at', sa.DateTime(), nullable=True),
    sa.Column('review_reply', sa.Text(), nullable=True),
    sa.Column('review_buyer_id', sa.Integer(), nullable=True),
    sa.Column('review_product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review_buyer_id'], ['buyers.user_id'], name='fk_reviews_buyer_id'),
    sa.ForeignKeyConstraint(['review_product_id'], ['products.product_id'], name='fk_reviews_product_id'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('shopping_carts',
    sa.Column('shopping_cart_buyer_id', sa.Integer(), nullable=False),
    sa.Column('shopping_cart_product_id', sa.Integer(), nullable=False),
    sa.Column('shopping_cart_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shopping_cart_buyer_id'], ['buyers.user_id'], name='fk_shopping_carts_buyer_id'),
    sa.ForeignKeyConstraint(['shopping_cart_product_id'], ['products.product_id'], name='fk_shopping_carts_product_id'),
    sa.PrimaryKeyConstraint('shopping_cart_buyer_id', 'shopping_cart_product_id')
    )
    op.create_table('sub_orders',
    sa.Column('sub_order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub_order_total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('sub_order_status', sa.Enum('pending', 'processing', 'shipped', 'delivered', 'cancelled', 'returned', name='order_status_enum'), nullable=False),
    sa.Column('sub_order_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sub_order_order_id'], ['orders.order_id'], name='fk_sub_orders_order_id'),
    sa.PrimaryKeyConstraint('sub_order_id')
    )
    op.create_index(op.f('ix_sub_orders_sub_order_status'), 'sub_orders', ['sub_order_status'], unique=False)
    op.create_table('voucher_orders',
    sa.Column('voucher_order_voucher_id', sa.Integer(), nullable=False),
    sa.Column('voucher_order_order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['voucher_order_order_id'], ['orders.order_id'], name='fk_voucher_orders_order_id'),
    sa.ForeignKeyConstraint(['voucher_order_voucher_id'], ['vouchers.voucher_id'], name='fk_voucher_orders_voucher_id'),
    sa.PrimaryKeyConstraint('voucher_order_voucher_id', 'voucher_order_order_id')
    )
    op.create_table('offer_requests',
    sa.Column('offer_request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('offer_request_sub_order_id', sa.Integer(), nullable=False),
    sa.Column('offer_request_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('offer_request_status', sa.Enum('pending', 'accepted', 'rejected', name='offer_request_status_enum'), nullable=False),
    sa.Column('offer_request_note', sa.String(length=255), nullable=True),
    sa.Column('offer_request_created_at', sa.DateTime(), nullable=True),
    sa.Column('offer_request_end_user_id', sa.Integer(), nullable=False),
    sa.Column('offer_request_sub_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_request_end_user_id'], ['end_users.user_id'], name='fk_offer_requests_end_user_id'),
    sa.ForeignKeyConstraint(['offer_request_sub_id'], ['offer_requests.offer_request_id'], name='fk_offer_requests_sub_id'),
    sa.ForeignKeyConstraint(['offer_request_sub_order_id'], ['sub_orders.sub_order_id'], name='fk_offer_requests_sub_order_id'),
    sa.PrimaryKeyConstraint('offer_request_id')
    )
    op.create_index(op.f('ix_offer_requests_offer_request_status'), 'offer_requests', ['offer_request_status'], unique=False)
    op.create_table('order_items',
    sa.Column('order_item_sub_order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_product_id', sa.Integer(), nullable=False),
    sa.Column('order_item_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_product_id'], ['products.product_id'], name='fk_order_items_product_id'),
    sa.ForeignKeyConstraint(['order_item_sub_order_id'], ['sub_orders.sub_order_id'], name='fk_order_items_sub_order_id'),
    sa.PrimaryKeyConstraint('order_item_sub_order_id', 'order_item_product_id')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_content', sa.String(length=500), nullable=False),
    sa.Column('question_reply', sa.String(length=500), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.bid_id'], name='fk_questions_bid_id'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.user_id'], name='fk_questions_seller_id'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('refunds',
    sa.Column('refund_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('refund_sub_order_id', sa.Integer(), nullable=False),
    sa.Column('refund_reason', sa.Text(), nullable=False),
    sa.Column('refund_status', sa.Enum('pending', 'approved', 'rejected', 'processed', name='refund_status_enum'), nullable=False),
    sa.Column('refund_created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['refund_sub_order_id'], ['sub_orders.sub_order_id'], name='fk_refunds_sub_order_id'),
    sa.PrimaryKeyConstraint('refund_id')
    )
    op.create_index(op.f('ix_refunds_refund_status'), 'refunds', ['refund_status'], unique=False)
    op.create_table('review_likes',
    sa.Column('review_like_review_id', sa.Integer(), nullable=False),
    sa.Column('review_like_buyer_id', sa.Integer(), nullable=False),
    sa.Column('review_like_created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_like_buyer_id'], ['buyers.user_id'], name='fk_review_likes_buyer_id'),
    sa.ForeignKeyConstraint(['review_like_review_id'], ['reviews.review_id'], name='fk_review_likes_review_id'),
    sa.PrimaryKeyConstraint('review_like_review_id', 'review_like_buyer_id')
    )
    op.create_table('save_documents',
    sa.Column('sd_bid_document_id', sa.Integer(), nullable=False),
    sa.Column('sd_bid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sd_bid_document_id'], ['bid_documents.bid_document_id'], name='fk_save_documents_doc_id'),
    sa.ForeignKeyConstraint(['sd_bid_id'], ['bids.bid_id'], name='fk_save_documents_bid_id'),
    sa.PrimaryKeyConstraint('sd_bid_document_id', 'sd_bid_id')
    )
    op.create_table('shipments',
    sa.Column('shipment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_sub_order_id', sa.Integer(), nullable=False),
    sa.Column('shipment_carrier', sa.String(length=100), nullable=False),
    sa.Column('shipment_status', sa.Enum('pending', 'shipped', 'in_transit', 'delivered', 'returned', name='shipment_status_enum'), nullable=False),
    sa.Column('shipment_created_at', sa.DateTime(), nullable=True),
    sa.Column('shipment_updated_at', sa.DateTime(), nullable=True),
    sa.Column('shipment_awb_no', sa.String(length=100), nullable=True),
    sa.Column('shipment_etd', sa.DateTime(), nullable=True),
    sa.Column('shipment_type', sa.Enum('normal', 'refund', name='shipment_type_enum'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_sub_order_id'], ['sub_orders.sub_order_id'], name='fk_shipments_sub_order_id'),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    op.create_index(op.f('ix_shipments_shipment_status'), 'shipments', ['shipment_status'], unique=False)
    op.create_table('submit_to_bids',
    sa.Column('stb_bid_document_id', sa.Integer(), nullable=False),
    sa.Column('stb_bid_id', sa.Integer(), nullable=False),
    sa.Column('stb_status', sa.Enum('submitted', 'accepted', 'rejected', name='stb_status_enum'), nullable=False),
    sa.Column('stb_created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stb_bid_document_id'], ['bid_documents.bid_document_id'], name='fk_submit_to_bids_doc_id'),
    sa.ForeignKeyConstraint(['stb_bid_id'], ['bids.bid_id'], name='fk_submit_to_bids_bid_id'),
    sa.PrimaryKeyConstraint('stb_bid_document_id', 'stb_bid_id')
    )
    op.create_index(op.f('ix_submit_to_bids_stb_status'), 'submit_to_bids', ['stb_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submit_to_bids_stb_status'), table_name='submit_to_bids')
    op.drop_table('submit_to_bids')
    op.drop_index(op.f('ix_shipments_shipment_status'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_table('save_documents')
    op.drop_table('review_likes')
    op.drop_index(op.f('ix_refunds_refund_status'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_table('questions')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_offer_requests_offer_request_status'), table_name='offer_requests')
    op.drop_table('offer_requests')
    op.drop_table('voucher_orders')
    op.drop_index(op.f('ix_sub_orders_sub_order_status'), table_name='sub_orders')
    op.drop_table('sub_orders')
    op.drop_table('shopping_carts')
    op.drop_table('reviews')
    op.drop_table('product_titles')
    op.drop_table('product_brands')
    op.drop_index(op.f('ix_payments_payment_status'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_bids_bid_status'), table_name='bids')
    op.drop_table('bids')
    op.drop_table('bid_products')
    op.drop_table('accumulate_points')
    op.drop_constraint("fk_products_shop", "products", type_="foreignkey")
    op.drop_index('idx_products_shop', table_name='products')
    op.drop_constraint('fk_products_category_id', 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_product_status'), table_name='products')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_index('idx_products_category_status', table_name='products')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_constraint("fk_operating_times_shop", "operating_times", type_="foreignkey")
    op.drop_index('idx_operating_times_shop', table_name='operating_times')
    op.drop_table('operating_times')
    op.drop_constraint("fk_follow_shops_shop", "follow_shops", type_="foreignkey")
    op.drop_index('idx_follow_shops_shop', table_name='follow_shops')
    op.drop_table('follow_shops')
    op.drop_table('buyer_vouchers')
    op.drop_table('withdrawal_histories')
    op.drop_index(op.f('ix_vouchers_voucher_ref_type'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_voucher_ref_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_voucher_discount_type'), table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_table('titles')
    op.drop_table('shops')
    op.drop_index(op.f('ix_reports_report_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_ref_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_ref_id'), table_name='reports')
    op.drop_index('idx_report_type_status', table_name='reports')
    op.drop_table('reports')
    op.drop_table('block_sellers')
    op.drop_table('bid_documents')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_tickets_ticket_status'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('sellers')
    op.drop_table('buyers')
    op.drop_index(op.f('ix_messages_message_ref_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_ref_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_logs_log_ref_type'), table_name='logs')
    op.drop_index(op.f('ix_logs_log_ref_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_table('has_notifications')
    op.drop_table('end_users')
    op.drop_table('admins')
    op.drop_index(op.f('ix_users_user_status'), table_name='users')
    op.drop_table('users')
    op.drop_table('searchs')
    op.drop_table('otps')
    op.drop_index(op.f('ix_notifications_notification_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_ref_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_ref_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('medias')
    op.drop_table('categories')
    op.drop_table('brands')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###