"""version 1.0.1

Revision ID: dba10f1ea3cc
Revises: 941560c1bffe
Create Date: 2025-12-22 21:07:56.650797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dba10f1ea3cc'
down_revision = '941560c1bffe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid_categorys',
    sa.Column('bc_bid_id', sa.Integer(), nullable=False),
    sa.Column('bc_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bc_bid_id'], ['bids.bid_id'], name='fk_bid_categorys_bid_id'),
    sa.ForeignKeyConstraint(['bc_category_id'], ['categories.category_id'], name='fk_bid_categorys_category_id'),
    sa.PrimaryKeyConstraint('bc_bid_id', 'bc_category_id')
    )
    op.add_column('bids', sa.Column('bid_sub_order_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('fk_bids_order_id'), 'bids', type_='foreignkey')
    op.create_foreign_key('fk_bids_sub_order_id', 'bids', 'sub_orders', ['bid_sub_order_id'], ['sub_order_id'])
    op.drop_column('bids', 'bid_order_id')
    op.create_unique_constraint('uq_otps_email', 'otps', ['otp_email'])
    op.add_column('sub_orders', sa.Column('sub_order_voucher_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_sub_orders_voucher_id', 'sub_orders', 'vouchers', ['sub_order_voucher_id'], ['voucher_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sub_orders_voucher_id', 'sub_orders', type_='foreignkey')
    op.drop_column('sub_orders', 'sub_order_voucher_id')
    op.drop_constraint('uq_otps_email', 'otps', type_='unique')
    op.add_column('bids', sa.Column('bid_order_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_bids_sub_order_id', 'bids', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bids_order_id'), 'bids', 'orders', ['bid_order_id'], ['order_id'])
    op.drop_column('bids', 'bid_sub_order_id')
    op.drop_table('bid_categorys')
    # ### end Alembic commands ###